### ISSUE TITLE
Support single objects for meta prop

### ISSUE THREAD

**Issue by joshwcomeau** [nfl/react-helmet#220]
While passing meta values to `<Helmet>`, the provided API is an array of objects:

```js
<Helmet
  meta={[
    { name: "description", content: "Helmet application" },
    { property: "og:type", content: "article" },
  ]}
/>
```

A co-worker recently tried passing a single object instead:

```js
<Helmet
  meta={{ name: "description", content: "Helmet application" }}
/>
```

The consequences of this were rather severe; because we render on the server, React Helmet's exception crashed a server crash. A careless deploy meant we spent quite a long time trying to figure out why our server kept going down.

Please understand that we accept responsibility for this, it was totally our fault for misunderstanding the documentation :)

That said, it could be helpful to prevent similar mistakes by other users to support the 'single object' syntax, for when only a single meta property needs to be set.

Would be happy to look into this and open a PR, if it's deemed a worthwhile inclusion!

Thanks.

**Comment by potench** [comment]
The `propType` is defined as an array of objects: https://github.com/nfl/react-helmet/blob/master/src/Helmet.js#L405 which will throw a warning in the JS console - but may require something like FlowType or TypeScript to catch earlier

**Comment by joshwcomeau** [comment]
So, at least when rendering on the server, the code doesn't make it to proptype checking. it throws the following exception while rendering:

```
TypeError: instanceTags.filter is not a function
   at /node_modules/react-helmet/lib/Helmet.js:122:22
   at Array.reduce (native)
   at getTagsFromPropsList (/node_modules/react-helmet/lib/Helmet.js:119:18)
   ...
```

That said, my point wasn't really to debate how the error should be handled. I was proposing extending the API to support _either_ an array of objects, or a single object.

But yeah, at the very least, I think there should be a try/catch used so that the entire app doesn't crash when an invalid prop is passed in.

**Comment by potench** [comment]
Open to discussion about changing `meta` shape to `Array | Object`, but I'd vote 👎 on overloading the `meta` propType because we want a strict/well-defined API.  

I know it's not your point, but, if we changed the shape of `meta` to `Object | Array` and you passed it a `String`... your app would still halt. 

If you pass any invalid prop to any of the server-side components in your app, how does your app handle the error? Does it always cause the server to halt? Are the errors difficult to debug? I'm not sure it makes sense for Helmet to try/catch or validate this one `meta` prop over any other prop since it doesn't fix the halting problem.

**Comment by joshwcomeau** [comment]
Yeah, fair enough. I see benefits to a strict API, as well as a forgiving one, and if you guys are going towards fixed, then that makes sense to me :)

So, the issue is that my server _doesn't_ handle the exception, since it's a JS error within React Helmet. 

I agree, after some thought, that a try/catch is far too general for this, but maybe there can be some on-update check to make sure none of the props passed in will cause a serious malfunction in the app? If it discovers that `instanceTags` is not an array, it can throw a `console.error` and give up rendering that instance, instead of calling `.filter` and having the language freak out.

The error in our case was extremely hard to debug, but mainly because we weren't looking in the right place. It was used on a side page, and it was crashing, but we were trying to figure out why the _main_ page was going unresponsive, while the server restarted.

Had we been a little wiser, we would have discovered the source of the error more quickly, but it's still pretty far from intuitive. It's a pretty big leap from `instanceTags.filter is not a function` to "Oh, I need to wrap my meta object in an array".

Ultimately it's you and your team's call :) I think some pain could be saved by making it easier to spot this error, but it's not a bug in your code, it's a bug in us humans haha.

**Comment by doctyper** [comment]
It's a valid point, we should explore throwing a more descriptive error when users provide invalid values.

I believe we're planning on adding and exporting Flow types to Helmet, which will also surface those errors to developers who use Flow types.

**Comment by jeffboyus** [comment]
It will be interesting watching this issue more. The React dev team has already put the writing on the wall that PropType checking will cease to exist going forward.  They are already telling people that Flow and TypeScript could be an alternative for some.

With PropType checking being removed (Maybe in version 16.x), some of this will now fall back on React-Helmet will it not?

**Comment by joshwcomeau** [comment]
Thanks @potench!  #233 is awesome.

@jeffboyus I _believe_ that they've since walked back the statement about ditching PropTypes. Unless there's news that they've committed to removing them, I wouldn't speculate.
