### ISSUE TITLE
`meta` is broken when server side rendering

### ISSUE THREAD

**Issue by gocreating** [nfl/react-helmet#96]
```js
// react part

export default class BaseLayout extends React.Component {
  render() {
    return <div>
      <Helmet
        title={this.props.title}
        meta={[
          {'charSet': 'utf-8'},
        ]} />
      {styles}
      {this.props.children}
      {scripts}
    </div>;
  }
};
```

```js
// server side rendering part

export function renderComponent(component) {
  const html = ReactDOMServer.renderToString(component);
  const head = Helmet.rewind();
  const title = head? head.title.toString(): '';
  console.log('head.meta', head.meta);
  const meta = head? head.meta.toString(): '';

  return (
    '<!DOCTYPE html>' +
    '<head>' +
      title +
      meta +
    '</head>' +
    '<body>' +
      '<div id="exseed_root">' +
        html +
      '</div>' +
    '</body>'
  );
};
```

```
// error message

TypeError: Cannot read property 'toLowerCase' of undefined
    at /Users/gocreating/projects/exseed-boilerplate/node_modules/react-helmet/lib/Helmet.js:177:47
    at Array.filter (native)
    at /Users/gocreating/projects/exseed-boilerplate/node_modules/react-helmet/lib/Helmet.js:141:22
    at Array.reduce (native)
    at getTagsFromPropsList (/Users/gocreating/projects/exseed-boilerplate/node_modules/react-helmet/lib/Helmet.js:138:18)
    at reducePropsToState (/Users/gocreating/projects/exseed-boilerplate/node_modules/react-helmet/lib/Helmet.js:443:19)
    at emitChange (/Users/gocreating/projects/exseed-boilerplate/node_modules/react-helmet/node_modules/react-side-effect/lib/index.js:47:15)
    at SideEffect.componentWillMount (/Users/gocreating/projects/exseed-boilerplate/node_modules/react-helmet/node_modules/react-side-effect/lib/index.js:88:9)
    at [object Object].ReactCompositeComponentMixin.mountComponent (/Users/gocreating/projects/exseed/node_modules/react/lib/ReactCompositeComponent.js:210:12)
    at [object Object].wrapper [as mountComponent] (/Users/gocreating/projects/exseed/node_modules/react/lib/ReactPerf.js:66:21)
    at Object.ReactReconciler.mountComponent (/Users/gocreating/projects/exseed/node_modules/react/lib/ReactReconciler.js:37:35)
    at [object Object].ReactCompositeComponentMixin.mountComponent (/Users/gocreating/projects/exseed/node_modules/react/lib/ReactCompositeComponent.js:225:34)
    at [object Object].wrapper [as mountComponent] (/Users/gocreating/projects/exseed/node_modules/react/lib/ReactPerf.js:66:21)
    at Object.ReactReconciler.mountComponent (/Users/gocreating/projects/exseed/node_modules/react/lib/ReactReconciler.js:37:35)
    at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (/Users/gocreating/projects/exseed/node_modules/react/lib/ReactMultiChild.js:241:44)
    at ReactDOMComponent.Mixin._createContentMarkup (/Users/gocreating/projects/exseed/node_modules/react/lib/ReactDOMComponent.js:591:32)
```

It is the `head.meta` that raises error
(while `head.title` doesn't cause error)
Anybody know what happened?

**Comment by gocreating** [comment]
I found the reason.
react-helmet only allows valid meta attributes, and `charSet` attribute is invalid in my code.
Just change it to `charset`:

```js
meta={[
  {'charSet': 'utf-8'},
]}
```

**Comment by gbrassey** [comment]
just to be clear, you made it lowercase 

```
meta={[
  {'charset': 'utf-8'},
]}
```
